sudo: required

language: go

go:
  - 1.16.13

services:
  - docker

script:
  ./build.sh pd-reassign-all

before_deploy:
  - docker login --username="geonet+dockerbuild" --password="${docker_password}" quay.io

deploy:
  skip_cleanup: true
  provider: script
  script: ./push.sh pd-reassign-all
  on:
    branch: main

notifications:
  email: false
  slack:
    if: branch in (main, staging, production)
    on_success: never
    on_failure: always
    on_pull_requests: false
    secure: mdLzzBjyxgc0VSl1/7KIdaeOR4bnwkdTjt7YyEiwVoTJHyzK27GoxZytCvTqtW7d95c/ejJAGNK8xlQ2XVjgwCekz6lv7yJ6Rve9v8hkeYJwaIJMUdliy0RpbpotIVweeAAKtEHe5dyO7WH7UJk463WcfOl+qqii0W9zQ19oww8f7QC0STIPf+7xwYBUHOBFelaP2vrA4SsXb6XRhJD5726yK9wN/SPT9i3wzui/2CPuh02oFQGmgA8k8Pg1Nm6GSN3P+lbKGLVzwHFu0kVs/2TyOaOZSAhh3RnL+VErCipLCxJR+ByiFXnuHma3fIpmAXiSmjLvbRGv9k46ivw77Qn5TPCTF1HoBB7CO9LHOOHq/Q2AiIzGNjarzizPmojdGDybWGBXJyDi0K+sHD4/6S70qyiF/t1MRXe4FdO9Ve/9hJ4kb3guOWdBPrjGi2J5E+IenVJPULuWQT6/73PX4GchkVpmzSa6OolKYruHn9U7UrwHG+Of08rB90y9dVa+pBSa8YiEaRtAdeXRU0RaKWhfhhyXGeIOrdZYwA4oMpQFTwtya2om2b0P1ujofrgq4DBfVyp4yCz6KvSIC81pxGOLpqFkBjlOVsfxyVwpXd4hvtPjUV0iTi34fObelJ/dRQ4RK5JO+g2ot/jcXxdNQ9X0Ls+tAMvQR/u9P8EIcpU=

env:
  global:
    - ALPINE_VERSION=3.8
    - secure: "uIa2VmPHKppdep5cX00HkLtNAUqNFx+J1qapKGw9BLxEkxcslV4fuSGLjC9jJC4tnC61TZeJSto0sUivkPYiWBUGPz/koiEjqJoFzCmVOxP5rxOw0OFsk5CAtFpPxeQKbW5sclbZlybJ/YAq30k8aDA4WLlMGo46I4LuNGnGak8j9rKmKxs7nWx4eBk/US5+Bi3BSWVfU3wJKP3xIm4j9pX6CK+VAbDX4kuc39IEuSqeO7Wt2CsPHI7uNWHXiBVVFZW44c9fECwER3PplLr+Tz6vcWAPusyI3k3X+8ZgL2ndiBStXqcmvXNz30CWl87gYejywBg4KCFbM3PpJ2uhCsxsZ/DUWI7Ih+TmPB2HTIpQq70cfE+ZvmsXTGXvASRUQ3Xbf0URP5/FAm5o3cyMkkLJbcQC9JilXsBOHKmZEaA0RmAm6R5tHdpFWFqfVnyOvYOg2e0ps5rQRGKiSszoofqvwExeTUe1VPuitIqF59okuEGtiIJgikzxRDlnN1cwUIgHnvFtaZM++cQQ8GC0JFs1mSq3jsmn1pOVY3WoWj6VgPdMla2pnaqSHR0Ap7Zki5YQDbkDxc+znrTpE2X10JzVncNXRKUjpud023+t/1w3obyHa5GycgYEgKJZJNP6+BPqraJioTEvwPz9HLsD6MrEWwknR27hnZD/CcSZnt8=" # docker_password

#  vim: set ts=2 sw=2 tw=0 et:
