---
name: Go container packaging

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"
  release:
    types: [published]
  workflow_dispatch: {}

permissions:
  actions: read
  packages: write
  contents: write
  pull-requests: write
  id-token: write
  security-events: write
  statuses: write
  checks: write

jobs:

  vars:
    runs-on: ubuntu-latest
    outputs:
      short-sha: ${{ steps.commit.outputs.short-sha }}
      current-date: ${{ steps.commit.outputs.current-date }}
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: examine commits details
        id: commit
        run: |
          echo "short-sha=$(git rev-parse --short HEAD)" >> "$GITHUB_OUTPUT"
          echo "current-date=$(TZ='Pacific/Auckland' date +'%Y%m%d%H%M%S')" >> "$GITHUB_OUTPUT"

  go-container-apps:
    uses: GeoNet/Actions/.github/workflows/reusable-go-container-apps.yml@main
    with:
      containerScanningEnabled: false # needs perms
      paths: >-
        ./cmd/pd-reassign-all

# vim: set ts=2 sw=2 tw=0 et:
